### ISSUE TITLE
Investigate GitHub packages (Docker image packaging)

### ISSUE THREAD

**Issue by gauthiermartin** [sonia-auv/docker-ros-airflow#92] opened 2020-01-10 17:16 UTC
Investigate how does github packages work and find out if it could be interesting to use in in our CI/CD effort.

**Comment by kevincharbonneau** [comment] 2020-01-31 14:34
duplicate of https://github.com/sonia-auv/documentation/issues/17

**Closed by kevincharbonneau** 2020-01-31 14:34 UTC
